server:
  port: 8882

spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/postgres
    username: postgres
    password: 136910@Mg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  messages:
    basename: locale/translation
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
